GET http://localhost:5000/usuarios
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzODcyOTMwMSwianRpIjoiM2M0NWYyOWMtZWYwMS00NWYyLThjYTktOTE3ZWEyZTQwMzRmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjM4NzI5MzAxLCJleHAiOjE2Mzg3MzAyMDF9.DyA7nfRVSlO5EOWBs94l8sHMr5TO9wtqEsQTj-gZTFE